### ISSUE TITLE
Error when combining three alignments

### ISSUE THREAD

**Issue by liubovch** [cbcrg/tcoffee#13]
Hi,

I was looking into the bug [#917143](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=917143) inside Debian and tried to reproduce it with the source that you provide from your [home page](http://www.tcoffee.org/Packages/Stable/Latest/). The failing command is:

```
./t_coffee -aln=../example/sproteases_small.muscle,../example/sproteases_small.tc_aln,../example/sproteases_small.b62_aln -outfile=combined-aln.aln
```
Here is the stderr of the command: [tcoffee.stderr.log](https://github.com/cbcrg/tcoffee/files/2800028/tcoffee.stderr.log)

It seems that there is a bug, but I find it difficult to start tracking it down based on the error message. Interestingly, that with two (not three) input alignments it doesn't fail.

EDITED: `t_coffee.ErrorReport` file doesn't get generated for some reason.

**Comment by tillea** [comment]
Hi,
I was also investigating into this problem.  The issue seems to be more complex.  When I run the command:

    t_coffee -aln sproteases_small.cw_aln sproteases_small.muscle sproteases_small.tc_aln -outfile combined_aln.aln

on a Debian testing system (future Debian 10) it works nicely.  However, if I run it on a Debian sid (aka unstable) system it breaks as Liubov reported.  I confirm that the ErrorReport is not created despite I added the -debug option.
Kind regards, Andreas.
