### ISSUE TITLE
Spaces in fully qualified path to executable cause t_coffee to fail

### ISSUE THREAD

**Issue by nivekkagicom** [cbcrg/tcoffee#2]
If t_coffee is installed in a directory where the path contains a space and the fully qualified path is passed on the command line as such:

`/Applications/Genetic\ Software/t_coffee -infile TCoffeeInput15_Mar_04_15_23_30_1 -outfile TCoffeeOutput15_Mar_04_15_23_30_2 -newtree TCoffeeInput15_Mar_04_15_23_30_1.dnd -output fasta_aln -type PROTEIN -dp_mode myers_miller_pair_wise`

t_coffee fails internally to handle the space in argv[0] with the following error:

`--ERROR:  : Software/t_coffee does not exist [FATAL]`
`*************************************************************************************************`
`*                        FULL TRACE BACK PID: 68544 `                      
`68544 -- ERROR:  : Software/t_coffee does not exist [FATAL]`

**Comment by pditommaso** [comment]
T-Coffee, like many linux tools does not support white spaces in PATH. I would suggest you avoid these things as they are very liley to result in issues, with either T-Coffee or other tools.

Furthermore, even if we were trying to fix it on T-Coffee. Since some the options rely on third party tools - most of which do not accept white spaces - the problem would most likely remain.
