### ISSUE TITLE
fmcoffee use 1 core

### ISSUE THREAD

**Issue by Sanrrone** [cbcrg/tcoffee#49]
Dears,
I am trying to run t_coffe with -mode fmcoffee, but it is not using additional cores. Also I tried
`t_coffee -in in.fasta -mode fmcoffee -thread 4 -n_core 4 -cpu 4 -multi_core 4 -max_n_proc 4 -outfile out.fasta`.
None of this flags works for fmcoffee step (kalign, muscle).

is there other flag to use multithread in fmcoffee mode?.

thanks in advance,
Sandro

**Comment by cnotred** [comment]
Hello

Are you using the latest beta? I think the Pb is fixed in that one 

Cheers 

Cedric 

###################################
Dr Cedric Notredame
Group Leader
Notredame's lab - Comparative Bioinformatics Group
Bioinformatics and Genomics Programme
Room 440.03

Centre de Regulació Genòmica (CRG)
Dr. Aiguader, 88
08003 Barcelona
Spain

Ph#     + 34 93 316 02 71
Fax#    + 34 93 316 00 99
Mobile# + 34 66 250 47 82

email   ***@***.***
url     www.tcoffee.org
blog    cedricnotredame.blogspot.com
ORC-ID: 0000-0003-1461-0988
###################################

**Comment by Sanrrone** [comment]
You are right,
the beta version works like a charm.

thanks!
