### ISSUE TITLE
Error building tcoffee with clang

### ISSUE THREAD

**Issue by slacka** [cbcrg/tcoffee#7]
When I try to build tcoffee with clang I get:
`dp_lib/evaluate_dirichlet.c:543:8: error: 'lgamma_r' is missing exception specification 'throw()'`

The same error log can be found here:
http://clang.debian.net/logs/2016-08-30/t-coffee_11.00.8cbe486-4_unstable_clang.log

**Comment by deliciouslytyped** [comment]
I ran into this via a completely unrelated issue (not related to tcoffee), the problem for me was that I was including libc++ before including glibc, this broke the resolution order of includes and, for example inside libc++ cmath.h, glibc's math.h was being included instead of libc++'s math.h; the proper order would have been cmath -> libc++/ math.h -> glibc/ math.h
